# .streamlit/config.toml
[theme]
primaryColor="#3D5E6B" # Cor principal para elementos como o botão
backgroundColor="#44474D" # Fundo mais escuro para conforto visual
secondaryBackgroundColor="#877C73" # Para sidebar ou elementos secundários (pode ser usado para o fundo de inputs também, como vamos fazer via CSS)
textColor="#D5D0C4" # Texto claro para contraste no fundo escuro
font="sans serif"

[server]
maxUploadSize = 10
